### PR TITLE
Add support for Palm, Claude-2, Llama2, CodeLlama (100+LLMs)

### PR DESCRIPTION
**Pull request by ishaan-jaff**
**Description:**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 

In addition LiteLLM client allows you to:
* A/B test LLMs in production 
* Dynamically control each LLMs prompt, temperature, top_k etc in our UI (no need to re-deploy code)
* Logging to view input/outputs for each LLM

Here's a link to a live demo of litellm client: https://admin.litellm.ai/ 

liteLLM-Ab-testing

**Reference Issues:** #XX (XX is the issue number you work on)

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@zqwerty @hsien1993 can I get a review on this PR ? 

Happy to add docs/tests if this initial commit looks good😊

**Comment by zqwerty** [comment]
Sorry for the late reply! I really appreciate your work! I will have a look in a few days.

**Comment by zqwerty** [comment]
Hi @ishaan-jaff , I really appreciate your work on providing a unified interface for LLMs. I am happy to use liteLLM to integrate many LLMs into ConvLab. I think the `liteLLM completion` can be used as a default implementation, instead of only replacing OpenAI API. So I will make a new PR and would like you to review it then. Thanks!

**Comment by ishaan-jaff** [comment]
@zqwerty sounds good - let me know. happy to look at the pr you make

**Comment by zqwerty** [comment]
Hi @ishaan-jaff , please have a look on #175

**Pull request closed without merging**
